<a href="https://www.kaggle.com/code/sinemkarahan/storygeneretor?scriptVersionId=198058323" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tinystories-narrative-classification/validation.csv
/kaggle/input/tinystories-narrative-classification/train.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/kaggle/input/tinystories-narrative-classification/train.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2119719 entries, 0 to 2119718
Data columns (total 1 columns):
 #   Column  Dtype
---  ------  -----
 0   text    object
dtypes: object(1)
memory usage: 16.2+ MB

In [5]:
df.head()

                                                text
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

In [6]:
import pandas as pd

df = pd.read_csv("/kaggle/input/tinystories-narrative-classification/train.csv")
print(df.info())  # Veri türleri ve eksik veriler hakkında bilgi almak için
print(df.head())  # İlk birkaç satırı görüntülemek için

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2119719 entries, 0 to 2119718
Data columns (total 1 columns):
 #   Column  Dtype
---  ------  -----
 0   text    object
dtypes: object(1)
memory usage: 16.2+ MB
None
                                                text
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

In [7]:
print(df.isnull().sum())  # Eksik veri sayısını kontrol et

text    230
dtype: int64

In [8]:
df.dropna(subset=['text'], inplace=True)
print(df.isnull().sum())  # Tekrar eksik veri kontrolü yapın

text    0
dtype: int64

In [9]:
import re

In [10]:
# Elle stopwords listesi oluşturalım (İngilizce için temel durak kelimeler)
stopwords = ['the', 'and', 'is', 'in', 'to', 'of', 'a', 'that', 'it', 'on', 'for', 'with', 'as', 'by', 'at', 'an', 'this', 'be', 'from', 'or']

# Temizlik fonksiyonunu güncelleyelim
def clean_text(text):
    if isinstance(text, str):  # Sadece string tipindeki değerlere işlem yap
        text = text.lower()  # Tüm metni küçük harfe çevirme
        text = re.sub(r'\d+', '', text)  # Sayıları kaldırma
        text = re.sub(r'[^\w\s]', '', text)  # Noktalama işaretlerini kaldırma
        text = ' '.join([word for word in text.split() if word not in stopwords])  # Durak kelimeleri çıkarma
        return text
    return text  # Eğer metin değilse (örneğin NaN veya sayı), olduğu gibi döndür

# Temizleme fonksiyonunu veri çerçevesine uygulama
df['cleaned_text'] = df['text'].apply(clean_text)

In [11]:
print(df[['text', 'cleaned_text']].head())

                                                text  \
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

                                        cleaned_text
0  one day little girl named lily found needle he...
1  once upon time there was little car named beep...
2  one day little fish named fin was swimming nea...
3  once upon time land full trees there was littl...
4  once upon time there was little girl named lil...

In [12]:
# İlk 5 satırı temizlenmiş metin sütunu ile görüntüleyin
print(df[['text', 'cleaned_text']].head())

                                                text  \
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

                                        cleaned_text
0  one day little girl named lily found needle he...
1  once upon time there was little car named beep...
2  one day little fish named fin was swimming nea...
3  once upon time land full trees there was littl...
4  once upon time there was little girl named lil...

In [13]:
import pandas as pd

# CSV dosyasını yükleme
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# Veri çerçevesinin ilk birkaç satırını görüntüleme
print(df.head())

                                                text
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

In [14]:
# 'cleaned_story' sütununun olup olmadığını kontrol etme
if 'cleaned_story' in df.columns:
    # Tekrar eden satırları kaldırma
    df.drop_duplicates(subset='cleaned_story', inplace=True)
    
    # Sonuçları kontrol etme
    print(df.head())
else:
    print("Veri çerçevesinde 'cleaned_story' adlı bir sütun bulunamadı.")

Veri çerçevesinde 'cleaned_story' adlı bir sütun bulunamadı.

In [15]:
import pandas as pd

# CSV dosyasını yükleme
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# Sütun isimlerini görüntüleme
print(df.columns)

Index(['text'], dtype='object')

In [16]:
import pandas as pd

# Veri setini yükle
data = pd.read_csv("/kaggle/input/tinystories-narrative-classification/train.csv")

# İlk birkaç satırı görüntüleyerek doğru yüklendiğinden emin ol
data.head()

                                                text
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...

In [17]:
# Tekrar eden satırları bul ve kaldır
data_cleaned = data.drop_duplicates()

# Temizlenmiş veri setinin boyutlarını görüntüle
print(f"Orijinal veri seti boyutu: {data.shape}")
print(f"Temizlenmiş veri seti boyutu: {data_cleaned.shape}")

Orijinal veri seti boyutu: (2119719, 1)
Temizlenmiş veri seti boyutu: (1799249, 1)

In [18]:
# Veri setindeki sütunları görüntüle
print(data.columns)

Index(['text'], dtype='object')

In [19]:
print(data_cleaned.isnull().sum())

text    1
dtype: int64

In [20]:
# Eksik satırları kaldır
data_cleaned = data_cleaned.dropna()

# Eksik veri olup olmadığını tekrar kontrol et
print(data_cleaned.isnull().sum())

text    0
dtype: int64

In [21]:
# Metinleri küçük harfe çevir
data_cleaned['text'] = data_cleaned['text'].str.lower()

In [22]:
import re

# Fazla boşlukları tek boşluğa indir
data_cleaned['text'] = data_cleaned['text'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

In [23]:
# Temizlenmiş verinin ilk birkaç satırını görüntüle
print(data_cleaned['text'].head())

0    one day, a little girl named lily found a need...
1    once upon a time, there was a little car named...
2    one day, a little fish named fin was swimming ...
3    once upon a time, in a land full of trees, the...
4    once upon a time, there was a little girl name...
Name: text, dtype: object

In [24]:
# Veri setindeki satır sayısını görmek
print(f"Veri setinde {data_cleaned.shape[0]} satır var.")

Veri setinde 1799248 satır var.

In [25]:
import tensorflow as tf
print(tf.__version__)  # TensorFlow'un yüklü olup olmadığını ve sürümünü kontrol edin

2.16.1

In [26]:
# NaN (boş) değerleri kaldırma
data_cleaned = data_cleaned.dropna(subset=['text'])

# Tüm verileri string'e çevirme ve fazla boşlukları temizleme
data_cleaned['text'] = data_cleaned['text'].astype(str).apply(lambda x: re.sub(r'\s+', ' ', x).strip())

# Temizlenmiş veriyi kontrol et
print(data_cleaned.head())

                                                text
0  one day, a little girl named lily found a need...
1  once upon a time, there was a little car named...
2  one day, a little fish named fin was swimming ...
3  once upon a time, in a land full of trees, the...
4  once upon a time, there was a little girl name...

In [27]:
import pandas as pd

# Veri setinizi yükleyin
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# İlk birkaç satırı görüntüleyin
print(df.head())

# Sütun isimlerini görüntüleyin
print(df.columns)

                                                text
0  One day, a little girl named Lily found a need...
1  Once upon a time, there was a little car named...
2  One day, a little fish named Fin was swimming ...
3  Once upon a time, in a land full of trees, the...
4  Once upon a time, there was a little girl name...
Index(['text'], dtype='object')

In [28]:
import pandas as pd

# Veri setini yükleyin
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# Eksik verileri kontrol edin
print(df.isnull().sum())

# Eksik verileri içeren satırları kaldırın
df = df.dropna(subset=['text'])

# Temizlenmiş veri setini kontrol edin
print(df.isnull().sum())

text    230
dtype: int64
text    0
dtype: int64

In [29]:
print(data_cleaned.head())

                                                text
0  one day, a little girl named lily found a need...
1  once upon a time, there was a little car named...
2  one day, a little fish named fin was swimming ...
3  once upon a time, in a land full of trees, the...
4  once upon a time, there was a little girl name...

In [30]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

# Veri setini yükleyin
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# Eksik verileri temizleyin
df = df.dropna(subset=['text'])

# Veri setinin küçük bir örneğiyle çalışın (örneğin, ilk 1000 satır)
df_sample = df.sample(1000)

# Metin verisini içeren sütunu alın
texts = df_sample['text'].values

# Metin verisini sayısal verilere dönüştürün
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

# NMF modelini oluşturun
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(X)

# Konu terimlerini inceleyin
for index, topic in enumerate(nmf_model.components_):
    print(f"Topic #{index}:")
    print([vectorizer.get_feature_names_out()[i] for i in topic.argsort()[-10:]])

Topic #0:
['day', 'little', 'named', 'play', 'girl', 'said', 'max', 'mom', 'mommy', 'lily']
Topic #1:
['named', 'didn', 'bird', 'loved', 'day', 'play', 'billy', 'boy', 'mom', 'timmy']
Topic #2:
['bird', 'girl', 'big', 'day', 'ball', 'little', 'sam', 'said', 'tim', 'tom']
Topic #3:
['tom', 'did', 'want', 'sorry', 'said', 'mom', 'says', 'anna', 'sara', 'ben']
Topic #4:
['race', 'jane', 'mary', 'day', 'park', 'mom', 'boy', 'said', 'jill', 'jack']

In [31]:
import numpy as np

# Her bir hikaye için NMF modelinin konu dağılımlarını al
topic_distributions = nmf_model.transform(X)

# En yüksek olasılığa sahip olan konuyu her hikaye için etiket olarak ata
df_sample['topic_label'] = np.argmax(topic_distributions, axis=1)

# Etiketlenmiş veriyi kontrol edelim
print(df_sample[['text', 'topic_label']].head())

                                                      text  topic_label
1291376  There was a baby elephant in the jungle and he...            2
590605   Once upon a time, there was a little boy named...            1
1804201  Once upon a time, there was a little boy named...            2
545564   Once upon a time, there was a pink bunny named...            2
1048984  The little boy was proud. He wanted to show ev...            2

In [32]:
# İlk 10 satırı görmek için
print(df_sample[['text', 'topic_label']].head(10))

# Belirli bir konuya ait hikayeleri görmek için (örneğin, 'topic_label' 2 olanlar)
print(df_sample[df_sample['topic_label'] == 2][['text', 'topic_label']])

# Tüm etiketi olan veriyi CSV dosyasına kaydetmek istersen:
df_sample.to_csv('etiketli_veri.csv', index=False)

                                                      text  topic_label
1291376  There was a baby elephant in the jungle and he...            2
590605   Once upon a time, there was a little boy named...            1
1804201  Once upon a time, there was a little boy named...            2
545564   Once upon a time, there was a pink bunny named...            2
1048984  The little boy was proud. He wanted to show ev...            2
332070   Mummy was playing with her little boy Toby. Sh...            2
1780523  Once upon a time there was a nice boy named Ja...            4
1525121  Once upon a time, there was a little boy. He w...            2
247377   Sara and Ben are friends. They like to play at...            3
784257   Mama was measuring something. It was a big oak...            2
                                                      text  topic_label
1291376  There was a baby elephant in the jungle and he...            2
1804201  Once upon a time, there was a little boy named...            2
545564   Once upon a time, there was a pink bunny named...            2
1048984  The little boy was proud. He wanted to show ev...            2
332070   Mummy was playing with her little boy Toby. Sh...            2
...                                                    ...          ...
293382   Once upon a time there was a three year old ca...            2
478090   Once upon a time, there was a bunny called Bro...            2
779762   Once upon a time, in a small town, there lived...            2
968321   Once there was a little girl called Joely. She...            2
432716   Once upon a time there was a delicate triangle...            2

[641 rows x 2 columns]

In [33]:
# Topic Label 0 olan hikayeleri gör
topic_0_stories = df_sample[df_sample['topic_label'] == 0]
print(topic_0_stories[['text', 'topic_label']])

# Topic Label 1 olan hikayeleri gör
topic_1_stories = df_sample[df_sample['topic_label'] == 1]
print(topic_1_stories[['text', 'topic_label']])

                                                      text  topic_label
676572   Once upon a time, there was a little girl name...            0
1768948  Lily likes to count. She counts her fingers, h...            0
279681   Once upon a time, there was a little girl name...            0
921609   Once upon a time, there was a little girl name...            0
500852   Once upon a time, there was a little girl name...            0
...                                                    ...          ...
40470    Once upon a time, a little girl named Lily was...            0
1229179  Once upon a time, there was a little bunny nam...            0
867765   Once upon a time, there was a little girl name...            0
1933186  Once upon a time, there was a little girl name...            0
96275    Lily was anxious. She wanted to wear her new d...            0

[157 rows x 2 columns]
                                                      text  topic_label
590605   Once upon a time, there was a little boy named...            1
1436499  Once upon a time, there was a little boy named...            1
13400    Once upon a time, there was a little boy named...            1
800390   Once upon a time, there was a big, fat bird na...            1
1965425  Once upon a time, there was a little boy named...            1
1925846  Once upon a time, there was a boy named Timmy....            1
908106   Once upon a time, there was a boy named Timmy....            1
1904200  Once upon a time, there was a little boy named...            1
2053217  Once upon a time, there was a little boy named...            1
2058499  Once upon a time, there was a boy named Timmy....            1
193481   One day, Timmy went to the gym with his mom. H...            1
251653   Once upon a time, there was a little boy named...            1
328138   Once upon a time, there was a little boy named...            1
1228603  Once upon a time, there was a little boy named...            1
1768243  Once upon a time, there was a little boy named...            1
270401   Once upon a time, there was a boy named Timmy....            1
1399716  Once upon a time, there was a boy named Timmy....            1
1664147  Once upon a time, there was a boy named Timmy....            1
196584   Once upon a time, there was a little boy named...            1
93897    Once upon a time, there was a boy named Timmy....            1
1884635  Once, there was a boy. His name was Timmy. He ...            1
1995198  Once upon a time, there was a little boy named...            1
595430   Once upon a time, there was a happy pupil name...            1
1802082  Timmy was very naughty. He loved playing with ...            1
1130973  Once upon a time, there was a little boy named...            1
262310   Once upon a time, there was a little boy named...            1
1350437  Once upon a time, there was a boy named Timmy....            1
2024878  Once upon a time, there was a little boy named...            1
1340487  Once upon a time, there was a little mouse nam...            1
288537   Once upon a time, there was a small boy named ...            1
1345947  Once upon a time, there was a kid named Timmy....            1
70927    Once upon a time, there was a boy named Timmy....            1
389727   Once upon a time, there was a little boy named...            1
1743411  Once upon a time, there was a little girl name...            1
1909835  Once upon a time, there was a little boy named...            1
158284   Once upon a time, there was a little girl name...            1
1181587  Once upon a time, there was a boy named Timmy....            1
1200933  Once upon a time, there was a little boy named...            1
2044444  Once upon a time, there was a charming hero na...            1
562877   Once upon a time, there was a little boy named...            1
1409811  Once upon a time, there was a little girl name...            1
1392066  Once upon a time, there were two friends named...            1
839367   Once upon a time, there was a little boy named...            1
1137659  Once upon a time, there was a little boy named...            1
614397   Once upon a time, there was a little boy named...            1
1425573  Once upon a time, there was a little boy named...            1
1835159  Once upon a time, there was a little boy named...            1
1493260  Once upon a time, there was a dog named Spot. ...            1
1895357  Once upon a time, there was a boy named Timmy....            1
611283   Once upon a time, there was a kind boy named T...            1
13334    Once upon a time, there was a little boy named...            1
1786847  Once upon a time, there was a boy named Timmy....            1
177499   Once upon a time, there was a little boy named...            1
1494993  Once upon a time, there was a boy named Timmy....            1
545490   Once upon a time, there was a little girl name...            1
193083   Once upon a time, there was a little boy named...            1
1122587  Once upon a time, there was a little boy named...            1
796983   Timmy was a small three year old. One day, he ...            1
1783889  Once upon a time, there was a little boy named...            1

In [34]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Text verisini hazırlayın (girdi verisi olarak kullanacağız)
texts = df_sample['text'].values

# Tokenizer oluşturun
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

# Metinleri sayısal verilere dönüştürün (tokenizasyon)
sequences = tokenizer.texts_to_sequences(texts)

# Verileri aynı uzunluğa getirin (padding işlemi)
maxlen = 100  # Giriş uzunluğu olarak 100 seçtim, bunu ihtiyaca göre artırabilirsiniz
X = pad_sequences(sequences, maxlen=maxlen)

# Konu etiketlerini hedef değerler (output) olarak kullanacağız
y = df_sample['topic_label'].values

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# Modeli oluşturun
model = Sequential()

# Embedding katmanı (her kelimeyi bir vektör temsil edecek)
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=50))

# RNN katmanı
model.add(SimpleRNN(128, return_sequences=False))

# Çıkış katmanı (5 farklı konu olduğu için)
model.add(Dense(5, activation='softmax'))

# Modeli derleyin
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Modeli eğitin
model.fit(X, y, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.5490 - loss: 1.2895 - val_accuracy: 0.6250 - val_loss: 1.1042
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.6104 - loss: 1.1827 - val_accuracy: 0.6250 - val_loss: 1.1143
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.6563 - loss: 1.0533 - val_accuracy: 0.6250 - val_loss: 1.1122
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.6318 - loss: 0.9941 - val_accuracy: 0.6250 - val_loss: 1.1233
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.6668 - loss: 0.8779 - val_accuracy: 0.6250 - val_loss: 1.1308
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7144 - loss: 0.7910 - val_accuracy: 0.6100 - val_loss: 1.1811
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8795 - loss: 0.4376 - val_accuracy: 0.6100 - val_loss: 1.3185
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.9121 - loss: 0.2878 - val_accuracy: 0.5100 - val_loss: 1.4336
Epoch 9/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9757 - loss: 0.1608 - val_accuracy: 0.4800 - val_loss: 1.5999
Epoch 10/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 1.0000 - loss: 0.0663 - val_accuracy: 0.4600 - val_loss: 1.6723

In [36]:
# Yeni bir kelime girdisi verelim
new_input = ['dog']

# Tokenizer kullanarak yeni girdiyi sayısal forma dönüştürelim
new_sequence = tokenizer.texts_to_sequences(new_input)
new_sequence = pad_sequences(new_sequence, maxlen=maxlen)

# Modelin tahminini alalım
predicted_topic = model.predict(new_sequence)

# En yüksek olasılıkla tahmin edilen konuyu belirleyelim
predicted_label = np.argmax(predicted_topic)

# O konuya ait bir hikaye seçip yazdıralım
predicted_story = df_sample[df_sample['topic_label'] == predicted_label].sample(1)['text'].values[0]
print(f"Tahmin edilen konu: {predicted_label}, Hikaye: {predicted_story}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step
Tahmin edilen konu: 2, Hikaye: Once upon a time there was a star. It was very hot in the sky and it shimmered brightly.

One day, an brave adventurer decided to reach up and touch the star. The moment the star was touched, it started to shrink. The adventurer was so excited! He shouted "Wow! It's shrinking!"

The star continued to shrink until it was no bigger than the adventurer's hand. The star was so small now that the adventurer decided to take it home and make a wish.

Back at home, the adventurer closed his eyes and made a wish. He wished for a million stars to rain down from the sky. Suddenly, the star in his hands started to grow bigger and bigger. It was so hot and so brilliant that he had to shield his eyes!

Suddenly, the sky opened up and a million stars began to rain down from the sky. The adventurer whisked his hand around and a million stars flew around it.

He looked up to the night sky and smiled, for he had made his wish come true!

In [37]:
# Üç kelimelik yeni bir girdi verelim
new_input = ['dog', 'play', 'park']

# Tokenizer kullanarak yeni girdiyi sayısal forma dönüştürelim
new_sequence = tokenizer.texts_to_sequences([' '.join(new_input)])
new_sequence = pad_sequences(new_sequence, maxlen=maxlen)

# Modelin tahminini alalım
predicted_topic = model.predict(new_sequence)

# En yüksek olasılıkla tahmin edilen konuyu belirleyelim
predicted_label = np.argmax(predicted_topic)

# O konuya ait bir hikaye seçip yazdıralım
predicted_story = df_sample[df_sample['topic_label'] == predicted_label].sample(1)['text'].values[0]
print(f"Tahmin edilen konu: {predicted_label}, Hikaye: {predicted_story}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Tahmin edilen konu: 2, Hikaye: Once upon a time, in a peaceful little town, there lived a cat named Tom. Tom loved to play with his ball all day. One day, Tom saw a new thing in the kitchen. It was green and smelled good. It was a mint plant.

Tom's mom said, "Tom, do not touch the mint. It is not for play." But Tom was curious. He wanted to try and play with the mint. So, when his mom was not looking, Tom took a leaf from the mint plant.

Tom played with the mint leaf and his ball. He had so much fun. But soon, his mom found out. She saw the mint leaf on the floor. "Tom, I told you not to touch the mint!" she said. Tom felt bad for not listening to his mom.

In the end, Tom learned to listen to his mom. He knew she was trying to keep him safe. Tom never touched the mint again. Instead, he played with his ball and had fun with his friends. And they all lived happily ever after.

In [38]:
# 'dog' kelimesini içeren hikayeleri filtrele
filtered_stories = df_sample[df_sample['text'].str.contains('dog', case=False)]

# Eğer bu kelimeyi içeren bir hikaye varsa, rastgele bir tanesini seç
if not filtered_stories.empty:
    predicted_story = filtered_stories.sample(1)['text'].values[0]
    print(f"'dog' kelimesini içeren hikaye: {predicted_story}")
else:
    print("'dog' kelimesini içeren bir hikaye bulunamadı.")

'dog' kelimesini içeren hikaye: One day, Judy was playing with her friends in the park when she noticed a little dog. She thought it was so cute that she wanted to bring it home. She asked her friends if she could take the dog home with her. Her friends said it was okay, so she picked it up and headed home.

When Judy got home, she put the dog on the floor. She quickly realised that her parents would not be happy if they knew she had brought a dog home without their permission. She looked around and noticed the ceiling. She had an idea - if she put the little dog up there, then her parents wouldn't know.

So, she put the little dog on the ceiling, where it stayed very still and quiet. But, as time passed, the little dog made lots of noise. Her parents heard the noise and recognized that it was coming from the ceiling. They went to investigate and saw Judy's little pet. Her parents were very upset and said she had been very modest.

Judy's parents were so angry with her that they sent the dog away. Judy cried, because she knew she had made a mistake and now she had lost her new pet. She recognised that she would not be able to get the little dog back.

In [39]:
# 'dog' kelimesini içeren hikayeleri filtrele
filtered_stories = df_sample[df_sample['text'].str.contains('dog', case=False)]

# Eğer bu kelimeyi içeren bir hikaye varsa, rastgele bir tanesini seç
if not filtered_stories.empty:
    predicted_story = filtered_stories.sample(1)['text'].values[0]
    print(f"'dog' kelimesini içeren hikaye: {predicted_story}")
else:
    print("'dog' kelimesini içeren bir hikaye bulunamadı.")

'dog' kelimesini içeren hikaye: Once upon a time, there was a dog named Max. Max loved to play outside with his friends. One day, something strange happened. Max found a bone in his backyard. He had never seen it before, so it was unknown to him. Max was so happy to have found the bone that he ran around the yard with it in his mouth.

Max's friends came over to play and saw the bone. They asked Max where he found it, but he didn't know. Max's friends were curious about the unknown bone, so they started to sniff around the yard. They found more bones! Max and his friends were so excited to have found these bones, they played with them all day long.

The next day, Max's owner came outside and saw the bones. She realized they were from a chicken that had died a long time ago. She took the bones away from Max and his friends to keep them safe. Max was sad that he couldn't play with his new bone anymore, but he was happy that he had a fun day with his friends.

In [40]:
model.save('model.h5')

In [41]:
import pickle
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [42]:
import os

# Mevcut çalışma dizinindeki dosyaları listele
for file in os.listdir():
    print(file)

.virtual_documents
model.h5
etiketli_veri.csv
tokenizer.pkl

In [43]:
from IPython.display import FileLink

# Modeli indirin
FileLink(r'./model.h5')

# Tokenizer'ı indirin
FileLink(r'./tokenizer.pkl')

/kaggle/working/tokenizer.pkl

In [44]:
from IPython.display import FileLink

# Modeli indirin
FileLink(r'./model.h5')

/kaggle/working/model.h5

In [45]:
from IPython.display import FileLink
FileLink(r'etiketli_veri.csv')

/kaggle/working/etiketli_veri.csv

In [46]:
import pandas as pd

# Dataset'i oku
df = pd.read_csv('/kaggle/input/tinystories-narrative-classification/train.csv')

# Dataset'i bilgisayara kaydet
df.to_csv('stories.csv', index=False)

KeyboardInterrupt: